
language: ruby

dist: trusty
sudo: false

before_install:
  - rvm get head
  - gem install bundler

rvm:
  - 2.2.5

script:
  - bundle exec rake db:create RACK_ENV="test"
  - bundle exec rake db:migrate
  - bundle exec rspec -color -fd
